### ISSUE TITLE
Syntax Error in PhonBrackets

### ISSUE THREAD

**Issue by savili** [aleixpol/solomagic#3]
I tried out PhonBrackets (I didn't test it though - I don't know how to) and the result is:
"SyntaxError: invalid syntax"

There are text.in/out files for PhonBrackets in the folder "deletion_tests" and testS9.py is the matching file to that.

I also tried PhonBrackets without the double quote at the end of the line (that didn't 
look so good to me) and the result is the same.
Here is the rule without the double quote at the end of the line:
"PhonBrackets": lambda record: createMa(record, lambda tier: re.sub(r"\((.)\)", "", word) for word in tier)),

And just in case I also tried this:
"PhonBrackets": lambda record: createMa(record, lambda tier: re.sub("\((.)\)", "", word) for word in tier)),"
and this:
"PhonBrackets": lambda record: createMa(record, lambda tier: re.sub("\((.)\)", "", word) for word in tier)),

Clearly I was monkeying around again and the result is the same in all cases.

I had based it on your suggestion for WeHateParenthesis, but I didn't do it right.
It'd be great to figure out how to do it better, so I can then complete the final few rules which will also require regex.

**Comment by aleixpol** [comment]
I fixed everything and now there's rainbows everywhere 🌈.

how sad is a black and white rainbow? 🌈 🌈

**Comment by savili** [comment]
I don't know. If I ever see one, I'll make sure to ask it.
Also they are colourful in the email :-)
Either way and especially coming from you they make me happy

So I wanted to try out the new PhonBrackets and this is what I did:
- I included PhonBrackets in the old-style (pre-solomagic1) solomagic.py and
I named the resulting file solomagicorigpb.py
 - I re-named the phonbrack.text.in file into phonbrack_mt.txt
 - I fed phonbrack_mt.txt to solomagicorigpb.py with createMa and PhonBrackets
and asked for phonbrack_ma1.txt
- This was the result:
Traceback (most recent call last):
  File "solomagicorigpb.py", line 106, in <module>
    cosa = [recordOperations[rule](record) for record in instance.records]
  File "solomagicorigpb.py", line 93, in <lambda>
    "PhonBrackets": lambda record: createMa(record, lambda tier: (re.sub(r"\((.+)\)", r"\1", word) for word in tier)),
  File "solomagicorigpb.py", line 86, in createMa
    record.setTier("\\ma", list(maTier))
  File "solomagicorigpb.py", line 93, in <genexpr>
    "PhonBrackets": lambda record: createMa(record, lambda tier: (re.sub(r"\((.+)\)", r"\1", word) for word in tier)),
NameError: global name 're' is not defined

- I also tried without createMa with the same result:
Traceback (most recent call last):
  File "solomagicorigpb.py", line 106, in <module>
    cosa = [recordOperations[rule](record) for record in instance.records]
  File "solomagicorigpb.py", line 93, in <lambda>
    "PhonBrackets": lambda record: createMa(record, lambda tier: (re.sub(r"\((.+)\)", r"\1", word) for word in tier)),
  File "solomagicorigpb.py", line 86, in createMa
    record.setTier("\\ma", list(maTier))
  File "solomagicorigpb.py", line 93, in <genexpr>
    "PhonBrackets": lambda record: createMa(record, lambda tier: (re.sub(r"\((.+)\)", r"\1", word) for word in tier)),
NameError: global name 're' is not defined


I don't think it's fully working yet

**Comment by savili** [comment]
It seems to be a more general regex thing.
I get the same for qataToXta:

Traceback (most recent call last):
File "solomagicorigpb.py", line 106, in <module>
cosa = [recordOperationsrule[rule](record) for record in instance.records]
File "solomagicorigregexta.py", line 93, in <lambda>
"qataToXta": lambda record: createMa(record, lambda tier: ("xta" if re.fullmatch(r"[q'][aeiou]ta", word) else word for word in tier)),
File "solomagicorigregexta.py", line 86, in createMa
record.setTier("\ma", list(maTier))
File "solomagicorigregexta.py", line 93, in <genexpr>
"qataToXta": lambda record: createMa(record, lambda tier: ("xta" if re.fullmatch(r"[q'][aeiou]ta", word) else word for word in tier)),
NameError: global name 're' is not defined
